export const SCENE_ICONS: Record<string, string> = {
  blank: "▢",
  home: "🏠",
  sea: "🌊",
  sky: "🌈",
  playground: "🛝",
  park: "🎡",
  mountain: "⛰️",
  beach: "🏖",
  river: "🌉",
  dino: "🦕",
  space: "🪐",
  school: "🏫",
  day: "🌞",
  night: "🌙",
  clear: "☀️",
  rain: "🌧",
  snow: "❄️",
  cloudy: "☁️",
  wind: "🌬",
  thunder: "⚡",
  stars: "✦",
  hearts: "♥",
  bubbles: "○",
};
